stages:
    - build

build:windows:
    tags:
        - windows
    stage: build
    # This file is a template, and might need editing before it works on your project.
    # Official language image. Look for the different tagged releases at:
    # https://hub.docker.com/r/library/python/tags/
    image: "python:3.8.5" 
    #commands to run in the Docker container before starting each job.
    before_script:
      - echo ${time}
      - echo "started by ${GITLAB_USER_NAME}"
      - choco install python --version=3.8.5 -y -f
      - python --version
      - pip install -r requirements.txt
    # different stages in the pipeline
    script:
      - pyinstaller main.spec
    artifacts:
        expire_in: '12 weeks'
        paths:
            - dist/main/

build:linux:
    tags:
        - linux
    stage: build
    # This file is a template, and might need editing before it works on your project.
    # Official language image. Look for the different tagged releases at:
    # https://hub.docker.com/r/library/python/tags/
    image: "python:3.8.5" 
    #commands to run in the Docker container before starting each job.
    before_script:
      - python --version
      - pip install -r requirements.txt
    # different stages in the pipeline
    script:
      - pyinstaller main.spec
    artifacts:
        expire_in: '12 weeks'
        paths:
            - dist/main/